### PR TITLE
Fix requirements dependency resolution on startup of core

### PR DESCRIPTION
**Pull request by chrisgemignani**
Ticket: None
Fix

Attempting to install 

```
$ /venv/bin/pip install -U -q -r requirements.txt -r requirements_dev.txt
```

puts pip into a very long dependency resolution as it tries to resolve awscli differences between requirements.txt and requirements_dev.txt. We can't see any this because we are running quiet. This PR just installs requirements and doesn't perform the upgrade check on all packages.

```
 Downloading awscli-1.19.43-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 16.9 MB/s
  Downloading awscli-1.19.42-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 13.6 MB/s
  Downloading awscli-1.19.41-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 21.4 MB/s
  Downloading awscli-1.19.40-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 7.1 MB/s
  Downloading awscli-1.19.39-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 15.4 MB/s
  Downloading awscli-1.19.38-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 20.9 MB/s
  Downloading awscli-1.19.37-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 23.7 MB/s
  Downloading awscli-1.19.36-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 20.8 MB/s
  Downloading awscli-1.19.35-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 20.2 MB/s
  Downloading awscli-1.19.34-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 23.0 MB/s
  Downloading awscli-1.19.33-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 18.7 MB/s
  Downloading awscli-1.19.32-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 27.8 MB/s
  Downloading awscli-1.19.31-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 19.4 MB/s
  Downloading awscli-1.19.30-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 18.5 MB/s
  Downloading awscli-1.19.29-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 18.3 MB/s
  Downloading awscli-1.19.28-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 21.2 MB/s
  Downloading awscli-1.19.27-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 16.6 MB/s
  Downloading awscli-1.19.26-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 15.1 MB/s
  Downloading awscli-1.19.25-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 14.7 MB/s
  Downloading awscli-1.19.24-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 20.6 MB/s
  Downloading awscli-1.19.23-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 17.4 MB/s
  Downloading awscli-1.19.22-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 13.0 MB/s
  Downloading awscli-1.19.21-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 14.4 MB/s
```

## Checklist

- [ ] Add information to the release notes documentation
- [ ] Add new feature to the usage documentation
- [ ] Add tests

### CODE REVIEW

**Review by cwire4 — COMMENTED** [review]
Does it still fail if you install the dev requirements but don't have the upgrade flag?

**Comment by chrisgemignani** [comment]
@cwire4 Yes, I think the issue comes with attempting to reconcile core requirements and the dev requirements

```
(venv) root@348f4606cc2f:/code# /venv/bin/pip install  -r requirements.txt -r requirements_dev.txt
INFO: pip is looking at multiple versions of bleach to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of azure-storage-blob to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of azure-core to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of azure-common to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of attrs to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of asn1crypto to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of aniso8601 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of secretstash to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of nose to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of geopatterns to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of drf-jwt to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements_dev.txt (line 1), awscli==1.19.57, boto3==1.14.63, botocore==1.17.63, google-auth==1.28.0, pyathena==1.4.3, rsa==4.7.2 and s3transfer==0.3.6 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.57 depends on botocore==1.20.57
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.58 depends on botocore==1.20.58
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.56 depends on botocore==1.20.56
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.55 depends on botocore==1.20.55
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.54 depends on botocore==1.20.54
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.53 depends on botocore==1.20.53
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.52 depends on botocore==1.20.52
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.51 depends on botocore==1.20.51
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.50 depends on botocore==1.20.50
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.49 depends on botocore==1.20.49
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.48 depends on botocore==1.20.48
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.47 depends on botocore==1.20.47
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.46 depends on botocore==1.20.46
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.45 depends on botocore==1.20.45
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.44 depends on botocore==1.20.44
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.43 depends on botocore==1.20.43
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.42 depends on botocore==1.20.42
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.41 depends on botocore==1.20.41
    The user requested rsa==4.7.2
    google-auth 1.28.0 depends on rsa<5 and >=3.1.4; python_version >= "3.6"
    awscli 1.19.40 depends on rsa<=4.5.0 and >=3.1.2
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.39 depends on botocore==1.20.39
    The user requested rsa==4.7.2
    google-auth 1.28.0 depends on rsa<5 and >=3.1.4; python_version >= "3.6"
    awscli 1.19.38 depends on rsa<=4.5.0 and >=3.1.2
    The user requested rsa==4.7.2
    google-auth 1.28.0 depends on rsa<5 and >=3.1.4; python_version >= "3.6"
    awscli 1.19.37 depends on rsa<=4.5.0 and >=3.1.2
    The user requested rsa==4.7.2
    google-auth 1.28.0 depends on rsa<5 and >=3.1.4; python_version >= "3.6"
    awscli 1.19.36 depends on rsa<=4.5.0 and >=3.1.2
    The user requested rsa==4.7.2
    google-auth 1.28.0 depends on rsa<5 and >=3.1.4; python_version >= "3.6"
    awscli 1.19.35 depends on rsa<=4.5.0 and >=3.1.2
    The user requested rsa==4.7.2
    google-auth 1.28.0 depends on rsa<5 and >=3.1.4; python_version >= "3.6"
    awscli 1.19.34 depends on rsa<=4.5.0 and >=3.1.2
    The user requested rsa==4.7.2
    google-auth 1.28.0 depends on rsa<5 and >=3.1.4; python_version >= "3.6"
    awscli 1.19.33 depends on rsa<=4.5.0 and >=3.1.2
    The user requested rsa==4.7.2
    google-auth 1.28.0 depends on rsa<5 and >=3.1.4; python_version >= "3.6"
    awscli 1.19.32 depends on rsa<=4.5.0 and >=3.1.2
    The user requested rsa==4.7.2
    google-auth 1.28.0 depends on rsa<5 and >=3.1.4; python_version >= "3.6"
    awscli 1.19.31 depends on rsa<=4.5.0 and >=3.1.2
    The user requested rsa==4.7.2
    google-auth 1.28.0 depends on rsa<5 and >=3.1.4; python_version >= "3.6"
    awscli 1.19.30 depends on rsa<=4.5.0 and >=3.1.2
    The user requested rsa==4.7.2
    google-auth 1.28.0 depends on rsa<5 and >=3.1.4; python_version >= "3.6"
    awscli 1.19.29 depends on rsa<=4.5.0 and >=3.1.2
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.28 depends on botocore==1.20.28
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.27 depends on botocore==1.20.27
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.26 depends on botocore==1.20.26
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.25 depends on botocore==1.20.25
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.24 depends on botocore==1.20.24
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.23 depends on botocore==1.20.23
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.22 depends on botocore==1.20.22
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.21 depends on botocore==1.20.21
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.20 depends on botocore==1.20.20
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.19 depends on botocore==1.20.19
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.18 depends on botocore==1.20.18
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.17 depends on botocore==1.20.17
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.16 depends on botocore==1.20.16
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.15 depends on botocore==1.20.15
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.14 depends on botocore==1.20.14
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.13 depends on botocore==1.20.13
    The user requested botocore==1.17.63
    boto3 1.14.63 depends on botocore<1.18.0 and >=1.17.63
    pyathena 1.4.3 depends on botocore>=1.5.52
    s3transfer 0.3.6 depends on botocore<2.0a.0 and >=1.12.36
    awscli 1.19.12 depends on botocore==1.20.12
    The user requested rsa==4.7.2
    google-auth 1.28.0 depends on rsa<5 and >=3.1.4; python_version >= "3.6"
    awscli 1.19.11 depends on rsa<=4.5.0 and >=3.1.2
    The user requested rsa==4.7.2
    google-auth 1.28.0 depends on rsa<5 and >=3.1.4; python_version >= "3.6"
    awscli 1.19.10 depends on rsa<=4.5.0 and >=3.1.2
    The user requested rsa==4.7.2
    google-auth 1.28.0 depends on rsa<5 and >=3.1.4; python_version >= "3.6"
    awscli 1.19.9 depends on rsa<=4.5.0 and >=3.1.2
    The user requested rsa==4.7.2
    google-auth 1.28.0 depends on rsa<5 and >=3.1.4; python_version >= "3.6"
    awscli 1.19.8 depends on rsa<=4.5.0 and >=3.1.2
    The user requested rsa==4.7.2
    google-auth 1.28.0 depends on rsa<5 and >=3.1.4; python_version >= "3.6"
    awscli 1.19.7 depends on rsa<=4.5.0 and >=3.1.2
    The user requested rsa==4.7.2
    google-auth 1.28.0 depends on rsa<5 and >=3.1.4; python_version >= "3.6"
    awscli 1.19.6 depends on rsa<=4.5.0 and >=3.1.2
    The user requested rsa==4.7.2
    google-auth 1.28.0 depends on rsa<5 and >=3.1.4; python_version >= "3.6"
    awscli 1.19.5 depends on rsa<=4.5.0 and >=3.1.2
    The user requested rsa==4.7.2
    google-auth 1.28.0 depends on rsa<5 and >=3.1.4; python_version >= "3.6"
    awscli 1.19.4 depends on rsa<=4.5.0 and >=3.1.2
    The user requested rsa==4.7.2
    google-auth 1.28.0 depends on rsa<5 and >=3.1.4; python_version >= "3.6"
    awscli 1.19.3 depends on rsa<=4.5.0 and >=3.1.2
    The user requested rsa==4.7.2
    google-auth 1.28.0 depends on rsa<5 and >=3.1.4; python_version >= "3.6"
    awscli 1.19.2 depends on rsa<=4.5.0 and >=3.1.2
    The user requested rsa==4.7.2
    google-auth 1.28.0 depends on rsa<5 and >=3.1.4; python_version >= "3.6"
    awscli 1.19.1 depends on rsa<=4.5.0 and >=3.1.2
    The user requested rsa==4.7.2
    google-auth 1.28.0 depends on rsa<5 and >=3.1.4; python_version >= "3.6"
    awscli 1.19.0 depends on rsa<=4.5.0 and >=3.1.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
WARNING: You are using pip version 21.0.1; however, version 21.1 is available.
You should consider upgrading via the '/venv/bin/python -m pip install --upgrade pip' command.
```

**Comment by chrisgemignani** [comment]
It's awscli in requirements_dev.txt. Maybe that's the better place to make this change

**Comment by chrisgemignani** [comment]
@cwire4 I have an update here. Trying to install requirements and requirements_dev together gets us into unresolvable dependency loop. Installing them sequentially merely results in some complaints. 

I tried to resolve this in the fruition requirements but this was unsuccessful. A few ideas for next steps

* awscli is added in this PR https://github.com/juiceinc/fruition/pull/2161 which was accompanied by growling and gnashing of teeth. Maybe there's a different way to do this now?
* create a pip-compiled dev requirements using requirements.txt as a constraint.
* use pip-sync to install and update requirements

**Review by cwire4 — APPROVED** [review]

**Pull request merged**
